name: Build and Test
on:
  push:
    branches: [ '*' ]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
